### ISSUE TITLE
Is it possible to get synonymous?

### ISSUE THREAD

**Issue by jaguarfi** [znck/grammarly#100]
In the official Grammarly websites, it is possible to get some synonymous suggestions by double-clicking the word.  Is that functionality somehow embedded in this extension?

**Comment by znck** [comment]
It shows synonyms when you select a word and press “cmd + .” on Mac (quick fix).

**Comment by ietz** [comment]
The quick fix synonym suggestions do not seem to work on my end. I can see a number of suggestions when using the Grammarly web app, but only see a "No code actions available" popover in VSCode.

As far as I can tell by looking through the commit history, the suggestions went from [an implementation](https://github.com/znck/grammarly/blob/937a5974d70ef95a20b54d4907d10e5f1c2de274/src/server/services/grammarly.ts#L212) to [a TODO](https://github.com/znck/grammarly/blob/8e1f0f2b1854b1c16ae282682ce39aeabf0a79b9/src/server/services/GrammarlyDiagnosticsService.ts#L228) with commit [8e1f0f2b](https://github.com/znck/grammarly/commit/8e1f0f2b1854b1c16ae282682ce39aeabf0a79b9). The TODO [was removed later on](https://github.com/znck/grammarly/commit/1ed857dba8deda73f143568fbc7019780833f0e8#diff-dfebcf8faffe5dbbb7befe0c3a67e99d9a318d176cbba0b792e98ac936b4c33bL243), but I could not find any code in the repo that actually searches for synonyms when calling the VSCode quick fix action since that commit.

Was this functionality removed, or am I missing something?
