### ISSUE TITLE
Add ability to only check on save

### ISSUE THREAD

**Issue by ChrisChinchilla** [znck/grammarly#108]
Thanks for the great extension! As far as I can tell, the extension checks pretty much after every change, or if you trigger the command manually from the command pallet. I wonder if it might be a good idea to add the ability to check on save instead, and maybe even make that default behaviour. This could possibly reduce any issues you might have with API limits (or however you are accessing the Grammarly service), and also performance and network hits from the client side.

Just a suggestion, happy to have a go at a PR myself if that sounds interesting to you.

**Comment by jaredmorgs** [comment]
I think this is why we're getting CAPTCHA errors after about a day.

+1 for "on save" as the default checking behaviour.

**Comment by ChrisChinchilla** [comment]
@znck I'm happy to give this a go, but quickly looking through the code, I am not sure how you trigger the checks? I can't seem to see any of the typical VSCode APIs

**Comment by ChrisChinchilla** [comment]
```
grammarly.autoActivate: Configures Grammarly activation behavior. When set to false, you need to run Grammarly: Check grammar errors to start Grammarly service.
```

Kind of solves this, but open to input

**Comment by jaredmorgs** [comment]
I thought this parameter only delays the start of the grammarly extension, but once started it still behaves as an always on always checking implementation

**Comment by znck** [comment]
The extension uses document change events to notify Grammarly API. Every document change event is converted to operational transform messages. In order to check only on save we need to create these operational transform messages by diffing document at last saved state and current save state. I started some work in the direction (https://github.com/znck/grammarly/compare/with-snapshot?expand=1) but I didn't get enough time to complete it. I am planning to revisit it again next month but if you wanna give it a try, you're welcome. Write to me if you need any help.

**Comment by ChrisChinchilla** [comment]
@znck I am happy to take a look, any chance you could assign this issue to me? (no permission), then I am more likely to find it later :)

**Comment by ChrisChinchilla** [comment]
I started looking at this, the code is complex, might take me a little while…
