### ISSUE TITLE
Feature Request: Enabling extension only in the comment blocks

### ISSUE THREAD

**Issue by santaimpersonator** [znck/grammarly#113]
### First of all, great extension... a lot of props on this! Thank you.

I occasionally write a bit of code, which is usually open source. Therefore, I comment pretty heavily in them for other users to understand what is going on. However... *(I bet you know where I am going with this is going)* there isn't a great tool for grammar checking in code and I think your extension is perfect for that.

**The request:**
Now, I understand your resistance to making this available for other file types as it would require a bunch of work on your part. Since your tool is free, I went on my own adventure to figure out how to enable your extension to search other files types (_it was easy enough to do, once I figured out where the extension files were placed on my computer_), so we can just ignore that. **I am only looking for a feature/function that enables me to search specific areas of a file**, like the comment block in most code... since that is the area with the most text.

**Note:** I might not be a developer, but I am happy to attempt this/stumble around on my own if you are willing to link me some info. on where to start and how to build the extension to test it out.

-Thanks!

**Edit:** Sorry if you saw a blank issue... my _butter_ finger hit the `Enter` key instead of the `Shift` key.

**Comment by franzbischoff** [comment]
Hello, first let me thank the developer for this extension. Now I can stop copy&paste my texts on Grammarly :-D

I'm adding a feature request on top of this one because I also agree with this request of "comment blocks".

I see also several requests to "enable the extension for file XYZ".

My suggestion is to disable the limitation of file type **when** you disable the `grammarly.autoActivate`. I think it should be nice to let the user enable the extension on whatever file he wants. My workaround has been to change the filetype to `plaintext` and later change back to the original language.

My 2 cents :-)
