### ISSUE TITLE
Support for MDX

### ISSUE THREAD

**Issue by JDansercoer** [znck/grammarly#26]
[MDX](https://mdxjs.com/) is a superset of Markdown that enables you to write React inside of a Markdown document.

Files have a `.mdx` extension.

I don't see the possibility of adding custom extensions, so is it possible to natively add support for it?

**Comment by andrew-codes** [comment]
For MDX support, it looks like the place to change was identified by the author on another issue: https://github.com/znck/grammarly/issues/28#issuecomment-586680757. Although it would be nice to be able to configure this instead of requiring a code change to enable a new extension/document type.

@znck Do you have any plans to enable this type of customization? I'm willing to submit a PR but want to ensure I wouldn't be duplicating efforts in case you already had an idea/something in development.

Thanks for putting this together, also. I have been torn on how to write content, but this eliminates my primary issue with using VS Code for writing, note-taking, etc.

**Comment by znck** [comment]
I haven’t been able to find time to work on it lately. If you’re interested, you can submit a PR for it.
