### ISSUE TITLE
Provide information when keytar fails due to in-availability of libsecret on linux

### ISSUE THREAD

**Issue by razvan-flavius-panda** [znck/grammarly#99]
Receiving the following error when trying to log in to Grammarly:

> Command 'Grammarly: Login to grammarly.com' resulted in an error (GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files)

And the extension does not show any issues highlighted even though on the Grammarly website there are 2 issues in that text.

I am running the extension version 0.12.1 on NixOS Linux.

**Comment by werunom** [comment]
I am also not able to login to grammarly. I get the same error as pointed above. 

Using the extension (after downloading the `vsix` file) in linux.

**Comment by werunom** [comment]
@znck --- can you please help how to resolve this issue?

**Comment by znck** [comment]
Need more information. Can you share extension log?

**Comment by werunom** [comment]
Extension version: 0.12.2 installed through `vsix` method
Vscode version: 1.45.1 
Operating system: Manjaro Linux

When I execute the command `Grammarly: Login to grammarly.com` say on a text file, the extension does _not_ produce any log. However, the following notification is shown: 
```
Command 'Grammarly: Login to grammarly.com' resulted in an error (GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files)
```
When I execute the command `Grammarly: Check grammar errors`, I get the following log:

```
(node:3118) UnhandledPromiseRejectionWarning: Error: Request $/credentials failed with message: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
    at handleResponse (/home/bhatta/.vscode/extensions/znck.grammarly-0.12.2/out/server.js:5232:48)
    at processMessageQueue (/home/bhatta/.vscode/extensions/znck.grammarly-0.12.2/out/server.js:5059:17)
    at Immediate.<anonymous> (/home/bhatta/.vscode/extensions/znck.grammarly-0.12.2/out/server.js:5043:13)
    at processImmediate (internal/timers.js:439:21)
(node:3118) UnhandledPromiseRejectionWarning: Error: Request $/credentials failed with message: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
    at handleResponse (/home/bhatta/.vscode/extensions/znck.grammarly-0.12.2/out/server.js:5232:48)
    at processMessageQueue (/home/bhatta/.vscode/extensions/znck.grammarly-0.12.2/out/server.js:5059:17)
    at Immediate.<anonymous> (/home/bhatta/.vscode/extensions/znck.grammarly-0.12.2/out/server.js:5043:13)
    at processImmediate (internal/timers.js:439:21)
(node:3118) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:3118) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)

```

Let me know if you need any further information. Thanks

**Comment by znck** [comment]
VS Code uses [keytar](https://github.com/atom/node-keytar) to store secrets (Grammarly password in our case). Do you have `libsecret` (required by keytar) installed on your system?

**Comment by werunom** [comment]
My OS has `libsecret (V 0.20.3)`.

Moreover, in the setup of this extension, where should I be providing/putting the Grammarly userID and password? Should I be mentioning it in `settings.json`?  (Checked the extension documents; nowhere this is mentioned.)

**Comment by znck** [comment]
Command `Grammarly: Login to grammarly.com` would launch an input prompt for username/password.

**Comment by werunom** [comment]
In that case, I am not sure what is the problem. Because I have `libsecret` and I get the above mentioned error (`GDBus.Error`) when I run the command `Grammarly: Login to grammarly.com`.

Any suggestion on how to resolve this?

**Comment by razvan-flavius-panda** [comment]
@znck I installed `libsecret` and still getting that error on login.

Do we also need to install `keytar` ?

**Comment by Gameransari** [comment]
The Solution is here  https://youtu.be/34iXHWuhsss

**Comment by werunom** [comment]
@znck - Glad to know that the extension is back! Can you please help us in resolving this issue? 

This time, in a freshly installed OS (Manjaro KDE), I tried again --- installed the extension from marketplace. But again the same error. 

So, looks like in linux systems, we need to do something else.

**Comment by Gameransari** [comment]
> @znck - Glad to know that the extension is back! Can you please help us in resolving this issue? 
> 
> 
> 
> This time, in a freshly installed OS (Manjaro KDE), I tried again --- installed the extension from marketplace. But again the same error. 
> 
> 
> 
> So, looks like in linux systems, we need to do something else.

See my upper comment.. the solution is in the video

**Comment by werunom** [comment]
@Gameransari --- had seen your video; but was not sure how is that a solution. 

Can you please give an explanation about it? For instance, what exactly happens with `--disable-wm-check`?

Also, your command and solution seems appropriate for xfce environment. What about KDE (which I use)?

**Comment by Gameransari** [comment]
> @Gameransari --- had seen your video; but was not sure how is that a solution. 
> 
> 
> 
> Can you please give an explanation about it? For instance, what exactly happens with `--disable-wm-check`?
> 
> 
> 
> Also, your command and solution seems appropriate for xfce environment. What about KDE (which I use)?

It's basically re-start or re-enable the stop service of desktop Menu. So disable wm make it to start desktop services which is already stopped

**Comment by pluth** [comment]
Ok so I don't understand how the linked Video relates to vscode or this issue at all...

On Arch Linux at least, this error is fixed by installing an optional dependency to libsecret that provides `org.freedesktop.secrets` as shown [here](https://www.archlinux.org/packages/core/x86_64/libsecret/) in the dependencies section.

**Comment by werunom** [comment]
> Ok so I don't understand how the linked Video relates to vscode or this issue at all...
> 
> On Arch Linux at least, this error is fixed by installing an optional dependency to libsecret that provides `org.freedesktop.secrets` as shown [here](https://www.archlinux.org/packages/core/x86_64/libsecret/) in the dependencies section.

@pluth --- no luck. I went to the page you pointed, and tried to install all the dependencies which were not present in my current setup of Manjaro. But no help. Still getting the same issue :(

**Comment by marcin-sucharski** [comment]
I've encountered similar issue. To solve it you have to provide some implementation of `org.freedesktop.secrets` like `gnome-keyring` or KeepassXC. In the NixOS case you can solve it using following configuration:
```nix
{
  services.gnome.gnome-keyring.enable = true;
}
```
On top of that, the keyring should be unlocked. By default this [happens upon login](https://github.com/NixOS/nixpkgs/blob/58a18d7056a8ad3728eb99252ccb2837c1444503/nixos/modules/services/desktops/gnome/gnome-keyring.nix#L52) (other distros should provide similar PAM-based solution). You can check if keyring is unlocked by running `seahorse` and looking for `Login`/`Default` collection.
Note that it is not strictly necessary to unlock keyring upon login.

With this configuration the issue with `org.freedesktop.secrets` should be solved.

However, when using manually configured distros (like Arch or NixOS) you may encounter another issue. After all, if keyring wasn't configured then it's likely that more things are missing. If you notice that after issuing login command nothing happens and after 5 minutes there is an error then you most likely have misconfigured default apps (xdg).

Currently, the plugin tries to [open URL for oauth](https://github.com/znck/grammarly/blob/2b5cdc087f4e376f40e0ccc28e0b328ff52e5039/extension/src/services/AuthenticationService.ts#L93-L97). Without default browser this operation will have no effect and you won't be able to complete authentication flow. In the case of NixOS you might fix it with following [Home Manager's](https://github.com/nix-community/home-manager) configuration:

```nix
{
  xdg.mimeApps.defaultApplications = {
    "x-scheme-handler/http" = "${pkgs.firefox-wayland}/share/applications/firefox.desktop";
    "x-scheme-handler/https" = "${pkgs.firefox-wayland}/share/applications/firefox.desktop";
    "x-scheme-handler/vscode" = "${vscodePackage}/share/applications/code-url-handler.desktop";
  };
}
```

Scheme handler for vscode is necessary, because confirmation url on the Grammarly's site will point to it.

Note that everything in this comment is specific to Linux distros and won't solve problems on Windows/MacOS.
